# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-22 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180921_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscriber', 'verbose_name_plural': 'Profiles'},
        ),
    ]
