# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-24 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180924_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='price_per_imem',
            new_name='price_per_item',
        ),
    ]
